app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    upvotes = db.Column(db.Integer)
    downvotes = db.Column(db.Integer)
    title = db.Column(db.String)
    content = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls):
        pitches = Pitch.query.order_by(Pitch.posted.desc()).all()
        return pitches

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    content = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls):
        comments = Comment.query.order_by(Comment.posted.desc()).all()
        return comments
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Required
from wtforms import TextAreaField,SubmitField,StringField

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Update bio.',validators = [Required()])
    submit = SubmitField('Save Changes')

class PostAPitch (FlaskForm):
    title = StringField('Title',validators = [Required()])
    content = TextAreaField('Pitch',validators = [Required()])
    submit = SubmitField('Pitch')

class PostAComment (FlaskForm):
    comment = TextAreaField(validators = [Required()])
    submit = SubmitField('Comment',validators = [Required()])

app/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
mail = Mail ()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required,current_user
from . import main
from .forms import UpdateProfile,PostAPitch,PostAComment
from .. import db,photos
from ..models import User,Pitch,Comment

@main.route('/')
def landingpage():

    return render_template('landingpage.html')

@main.route('/timeline',methods=['GET','POST'])
@login_required
def timeline():
    form = PostAPitch()
    if form.validate_on_submit():
        new_pitch = Pitch(upvotes=0,downvotes=0,title=form.title.data,content=form.content.data,user_id=current_user.id)
        new_pitch.save_pitch()
        return redirect(url_for('main.timeline'))
    pitches= Pitch.get_pitches()
    users = User.query.all()

    return render_template('timeline.html',form=form,pitches=pitches,users=users)
 
@main.route('/user/profile/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    pitches = Pitch.query.order_by(Pitch.posted.desc()).all()
    
    return render_template('profile.html', user = user, pitches=pitches)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('update.html',form=form,user =user)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.update_profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block styles %}
    {{super()}}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='try6.css') }}">
{% endblock %}

app/templates/index.html
{% import 'macros.html' as macro%}
<!DOCTYPE html>
<html>
    <head>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.5/css/mdb.min.css" rel="stylesheet">
        <title>Best Pitch</title>
    </head>
    <body style="font-family:'Rokkitt', serif; background-color: black;">
        <div id="content">{% block content %}{% endblock %}</div>
    </body>
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/js/mdb.min.js"></script>
    </html>

app/templates/landingpage.html
{% extends 'base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock%}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<div class="wrapper-view" id="firstpage">
    <div class="container-fluid">
        <div id="title">
            <h2 class="typewriter" style="color: white; text-align: center; font-weight: 40px; font-size: 70px;">Welcome to Bestpitch.</h2>
            <h4 style="color: white; text-align: center; font-weight: 40px; font-size: 40px;"> Get your idea out there</h4>
        </div>
        <div class="row" id="intro">
            <div class="col-md-4" class="menu" id="menu1">
                <a href="/timeline">
                    <i class="fas fa-comments"></i>
                    <p id="select1">Comment on ideas</p>
                </a>
        </div>
        <div class="col-md-4" class="menu" id="menu2">
            <a href="/timeline" >
                <i class="fas fa-lightbulb"></i>
                <p id="select2">Make a pitch</p>
            </a>
        </div>
        <div class="col-md-4" class="menu" id="menu3">
            <a href="/authenticate/login">
                <i class="fas fa-edit"></i>
                <p id="select3">Register / Login</p></a>
        </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<div class="nav navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="app/static/images/bestpitch.png">  </a>
        </div>
        <div class="nav navbar-nav navbar-right">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item">
                    <a class="nav-link active" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/timeline">Timeline</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/blog">Blog</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
                </li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>
</div

app/templates/profile.html
{% extends 'base.html'%}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<div class="wrapper-view" style="background-color: #ECE2D0;font-family: Arial, Helvetica, sans-serif;padding-bottom: 40px;">
    <div class="container-fluid" id="profilepage">
        <div class="row">
            <div class="col-md-4" >
                {% if user.profile_pic_path %}
                    <img src="{{url_for('static',filename=user.profile_pic_path)}}" style="margin-top:70px;"alt="" class="img-thumbnail" id="profpic">
                {%else%}
                    <i class="fas fa-camera" style="text-align:center;color:white;padding-top:8%;" id="profpic"></i>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row" id="profstats" style="font-weight: bold;font-size: 20px;text-align: center;">
            <div class="col-md-2">
                <p>Posts</p>
                <p>0</p>
            </div>
            <div class="col-md-2">
                <p>Following</p>
                <p>0</p>
            </div>
            <div class="col-md-2">
                <p>Followers</p>
                <p>0</p>
            </div>
            <div class="col-md-1">
                <a class="btn btn-lg" href="/user/{{user.username}}/update" role="button" style="margin-top:10px; color: purple;border:solid 1px purple;">Edit Profile</a>
            </div>
    </div>
    <div class="row" id="mainprofile">
            <div class="col-md-2" id="bio">
                {% if user %}
                    <p>@{{user.username}}</p>
                    <p>I'm feeling</p>
                    {% if user.bio %}
                        <h5 style="font-weight:bold;">Bio</h6>
                        <p> {{user.bio}}</p>
                    {%else%}
                        <p> {{user.username| capitalize}} has no bio </p>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-6" id="myposts">
                <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;height:50px;">
                    <div class="col-md-4">
                        <a style="color:purple;font-size: 20px;">My Posts</a>
                    </div>
                    <div class="col-md-4">
                        <a style="color:purple;font-size: 20px;">Liked Posts</a>
                    </div>
                    <div class="col-md-4">
                        <a style="color:purple;font-size: 20px;">Posts&Comments</a>
                    </div>
                </div>
                {% for pitch in pitches %}
                    {% if pitch.user_id == current_user.id %}
        <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-top:10px;padding-bottom: 10px;">
        <div class="col-md-2" >
                    {% if user.profile_pic_path %}
                        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" 
                        style="border-radius:50%; width:70px;height:70px;padding:0;">
                    {% endif %}
            </div>
            <div class="col-md-8">
                <div class="row">
                    {% for user in users %}
                        {% if user.id == pitch.user_id %}
                            <p style="font-weight: bold;">{{user.username}}</p>
                        {% endif %}
                    {% endfor %}
                    <p>{{pitch.title}}</p>
                    <p>{{pitch.content}}</p>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="row">
                            <div class="col-md-6">
                                <i class="fas fa-thumbs-up" style="font-size:20px;margin: 0;"></i>
                            </div>
                            <div class="col-md-4">
                                <p>{{pitch.upvotes}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                            <div class="row">
                                <div class="col-md-6">
                                        <i class="fas fa-thumbs-down" style="font-size:20px;margin: 0;"></i>
                                </div>
                                <div class="col-md-4">
                                        <p>{{pitch.downvotes}}</p>
                                </div>
                            </div>
                    </div>
                </div>
            </div>            
        </div>
        {% endif %}
        {% endfor %}
                <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-bottom: 10px;">
                    <div style="border-bottom: solid 4px purple;height:250px;">
                            <h4 style="font-weight: bold;text-align: center;margin-top:20px;">Welcome to Bestpitch {{user.username}}!</h4>
                            <p style="text-align: center;color: #A7A5C6; font-size: 20px;">You can start by posting a pitch and connecting with other users</p>
                            <a class="btn btn-primary btn-lg" href="/timeline" role="button" style="margin-left:250px;background-color: purple;color: white;border:purple;">First Pitch</a>
                            <div class="row">
                                <div class="col-md-4" style="margin-left:210px;">
                                    {% if user.profile_pic_path %}
                                        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" id="profpic" style="border:purple;">
                                    {%else%}
                                        <img src="https://image.freepik.com/free-vector/modern-abstract-background-with-purple-geometric-shapes-elements_1302-5268.jpg" alt="" class="img-thumbnail" id="profpic" style="border:purple;">
                                    {% endif %}
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3" id="utilities">
                <p>sjqhwDBJJDAWEDIWNDMWENM</p>
            </div>
        </div>
</div>
{% endblock %}

app/templates/timeline.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock%}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<div class="container-fluid" style="background-color: #ECE2D0;font-family: Arial, Helvetica, sans-serif;
padding-bottom: 40px;height:768px;overflow-x: hidden;overflow-y:scroll;">
    <div class="row" id="timeline">
    <div class="col-md-2" id="utilities">
        <div style="margin-left:40px;">
                {% for user in users %}
                {% if user.id == current_user.id %}
                    {% if user.profile_pic_path %}
                        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="border-radius:50%; width:100px;height:100px;">
                    {% endif %}
                    <p style="font-weight: bold;">@{{user.username}}</p>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="col-md-6" id="myposts">
            <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;height:50px;">
                    <div class="col-md-4">
                        <a style="color:purple;font-size: 20px;">My Timeline</a>
                    </div>
            </div>
        <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-bottom: 10px;">
            <div class="col-md-8" style="margin-left:100px;">
                    {{wtf.quick_form(form)}}
            </div>
        </div>
        {% for pitch in pitches %}
        <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-top:10px;padding-bottom: 10px;">
        <div class="col-md-2" >
            {% for user in users %}
                {% if user.id == pitch.user_id %}
                    {% if user.profile_pic_path %}
                        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" 
                        style="border-radius:50%; width:70px;height:70px;padding:0;">
                    {% endif %}
                {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-8">
                <div class="row">
                    {% for user in users %}
                        {% if user.id == pitch.user_id %}
                            <p style="font-weight: bold;">{{user.username}}</p>
                        {% endif %}
                    {% endfor %}
                    <p>{{pitch.title}}</p>
                    <p>{{pitch.content}}</p>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="row">
                            <div class="col-md-6">
                                <i class="fas fa-thumbs-up" style="font-size:20px;margin: 0;"></i>
                            </div>
                            <div class="col-md-4">
                                <p>{{pitch.upvotes}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-6">
                                        <i class="fas fa-thumbs-down" style="font-size:20px;margin: 0;"></i>
                                </div>
                                <div class="col-md-4">
                                        <p>{{pitch.downvotes}}</p>
                                </div>
                            </div>
                    </div>
                    <div class="col-md-2">
                            <button type="button" class="btn" data-toggle="modal" data-target="#myModal" style="background-color: purple;color:white;font:20px;">
                                    Comment
                                  </button>
                    </div>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
                {% for user in users %}
                    {% if user.id == pitch.user_id %}
                    <h5 class="modal-title" id="exampleModalLabel" style="font-weight:bold;">@{{user.username}} (Pitch: {{pitch.title}})</h5>
                    {% endif %}
                {% endfor %}
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="row">
                        <div class="col-md-4">
                                {% for user in users %}
                                 {% if user.id == current_user.id %}
                                 <p style="font-weight: bold;"> Comment by @{{user.username}}</p>
                                     {% if user.profile_pic_path %}
                                         <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="border-radius:50%; width:100px;height:100px;">
                                     {% endif %}
                                 {% endif %}
                             {% endfor %}
                         </div>
                         <div class="col-md-6">
                             nkdwe.laijfi.lwehfenmf mea f,weufejf dnm
                         </div>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
                </div>
                <div class="row">
                        {% if pitch.comments %}
                        <h4 style="font-weight: bold;">Comments</h4>
                            {%for comment in pitch.comments %}
                            <div class="col-md-10" style="height:100px;overflow-y:scroll;">
                            
                            </div> 
                            {% endfor %}
                        {% endif %}     
                    </div> 
                </div>
            </div>
            {% endfor %}
    </div>
    <div class="col-md-3" id="utilities">
        <p>sjqhwDBJJDAWEDIWNDMWENM</p>
    </div>
</div>
</div>
{% endblock %}

app/templates/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
<div class="wrapper-view" style="background-color: #ECE2D0;font-family: Arial, Helvetica, sans-serif;padding-bottom: 40px;">
    <div class="container-fluid" id="profilepage">
        <a href="/" class="row" style="text-decoration:none;">
            <i class="far fa-image" style="color:white;font-size:50px;margin-left:600px;"></i>
            <h2 style="color:white; text-align: center; font-weight: 40px; font-size: 20px;">Change cover photo</h2>
        </a>
        <div class="row">
            <div class="col-md-4">
                {% if user.profile_pic_path %}
                    <img src="{{url_for('static',filename=user.profile_pic_path)}}" style="margin-top: -110px;" alt="" class="img-thumbnail" id="profpic">
                {% if user == current_user %}
                    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                      <input type="file"  name="photo" class="form-control" required>
                      <input type="submit" style="margin:5px;">
                    </form>
                {% endif %}
                {%else%}
                <a href="/changeprofile" style="text-decoration:none;text-align: center;">
                    <div id="profpic" style="margin-top: -110px;">
                        {% if user == current_user %}
                            <form  style="margin-top:100px;" action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                              <input type="file"  name="photo" class="form-control" required>
                              <input type="submit" style="margin:5px;">
                            </form>
                        {% endif %}
                    </div>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row" style="margin-top:200px;margin-left:0;color:purple;">
        <div class="col-md-6">
            {{wtf.quick_form(form)}}
        </div>
    </div>

{% endblock %}